version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=nestjs
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3306:3306
    networks:
      - node_network

networks:
  node_network:
    name: node_network